name: Release plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.2
      - uses: actions/setup-node@v6
        with:
          node-version: lts/Jod
          cache: pnpm

      - name: Check versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          test "$tag" = "$(jq -r .version package.json)"
          test "$tag" = "$(jq -r .version manifest.json)"
          jq -e --arg v "$tag" 'has($v)' versions.json

      - name: Build plugin
        run: |
          pnpm install -r --frozen-lockfile
          pnpm build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css
